site_name: GhostBot
repo_url: https://github.com/Kwoth/NadekoBot
pages:
- 主頁: index.md
- 關於: about.md
- 指南:
    - Windows 指南: guides/Windows Guide.md
    - Linux 指南: guides/Linux Guide.md
    - OSX 指南: guides/OSX Guide.md
    - Docker 指南: guides/Docker Guide.md
    - 使用資源: guides/From Source.md
- 命令:
    - 說明: Readme.md
    - 英文命令列表: https://nadekobot.me/commands
    - 中文命令列表: Chinese Commands List.md
- 功能說明:
    - JSON 功能: JSON Explanations.md
    - 權限系統: Permissions System.md
    - 自定義回覆: Custom Reactions.md
    - 替代字符: Placeholders.md
- 常見問題: Frequently Asked Questions.md
- 貢獻指南: Contribution Guide.md
- ❤ 贊助 ❤: Donate.md

theme: readthedocs
